/* The following code was generated by JFlex 1.7.0 */

import java_cup . runtime . *;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>PL0.jflex</tt>
 */
class PL0Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\3\1\44\1\44\1\44\22\0\1\3\7\0\1\12"+
    "\1\13\1\16\1\14\1\6\1\15\1\5\1\17\12\2\1\20\1\4"+
    "\1\7\1\10\1\11\2\0\32\1\6\0\1\27\1\21\1\26\1\34"+
    "\1\22\1\35\1\23\1\41\1\24\2\1\1\30\1\1\1\25\1\31"+
    "\1\36\1\1\1\37\1\32\1\33\1\40\1\42\1\43\3\1\12\0"+
    "\1\44\44\0\1\1\12\0\1\1\4\0\1\1\5\0\27\1\1\0"+
    "\37\1\1\0\u01ca\1\4\0\14\1\16\0\5\1\7\0\1\1\1\0"+
    "\1\1\201\0\5\1\1\0\2\1\2\0\4\1\1\0\1\1\6\0"+
    "\1\1\1\0\3\1\1\0\1\1\1\0\24\1\1\0\123\1\1\0"+
    "\213\1\10\0\246\1\1\0\46\1\2\0\1\1\7\0\47\1\110\0"+
    "\33\1\5\0\3\1\55\0\53\1\25\0\12\2\4\0\2\1\1\0"+
    "\143\1\1\0\1\1\17\0\2\1\7\0\2\1\12\2\3\1\2\0"+
    "\1\1\20\0\1\1\1\0\36\1\35\0\131\1\13\0\1\1\16\0"+
    "\12\2\41\1\11\0\2\1\4\0\1\1\5\0\26\1\4\0\1\1"+
    "\11\0\1\1\3\0\1\1\27\0\31\1\107\0\25\1\1\0\10\1"+
    "\106\0\66\1\3\0\1\1\22\0\1\1\7\0\12\1\4\0\12\2"+
    "\1\0\20\1\4\0\10\1\2\0\2\1\2\0\26\1\1\0\7\1"+
    "\1\0\1\1\3\0\4\1\3\0\1\1\20\0\1\1\15\0\2\1"+
    "\1\0\3\1\4\0\12\2\2\1\23\0\6\1\4\0\2\1\2\0"+
    "\26\1\1\0\7\1\1\0\2\1\1\0\2\1\1\0\2\1\37\0"+
    "\4\1\1\0\1\1\7\0\12\2\2\0\3\1\20\0\11\1\1\0"+
    "\3\1\1\0\26\1\1\0\7\1\1\0\2\1\1\0\5\1\3\0"+
    "\1\1\22\0\1\1\17\0\2\1\4\0\12\2\11\0\1\1\13\0"+
    "\10\1\2\0\2\1\2\0\26\1\1\0\7\1\1\0\2\1\1\0"+
    "\5\1\3\0\1\1\36\0\2\1\1\0\3\1\4\0\12\2\1\0"+
    "\1\1\21\0\1\1\1\0\6\1\3\0\3\1\1\0\4\1\3\0"+
    "\2\1\1\0\1\1\1\0\2\1\3\0\2\1\3\0\3\1\3\0"+
    "\14\1\26\0\1\1\25\0\12\2\25\0\10\1\1\0\3\1\1\0"+
    "\27\1\1\0\20\1\3\0\1\1\32\0\3\1\5\0\2\1\4\0"+
    "\12\2\20\0\1\1\4\0\10\1\1\0\3\1\1\0\27\1\1\0"+
    "\12\1\1\0\5\1\3\0\1\1\40\0\1\1\1\0\2\1\4\0"+
    "\12\2\1\0\2\1\22\0\10\1\1\0\3\1\1\0\51\1\2\0"+
    "\1\1\20\0\1\1\5\0\3\1\10\0\3\1\4\0\12\2\12\0"+
    "\6\1\5\0\22\1\3\0\30\1\1\0\11\1\1\0\1\1\2\0"+
    "\7\1\37\0\12\2\21\0\60\1\1\0\2\1\14\0\7\1\11\0"+
    "\12\2\47\0\2\1\1\0\1\1\2\0\2\1\1\0\1\1\2\0"+
    "\1\1\6\0\4\1\1\0\7\1\1\0\3\1\1\0\1\1\1\0"+
    "\1\1\2\0\2\1\1\0\4\1\1\0\2\1\11\0\1\1\2\0"+
    "\5\1\1\0\1\1\11\0\12\2\2\0\4\1\40\0\1\1\37\0"+
    "\12\2\26\0\10\1\1\0\44\1\33\0\5\1\163\0\53\1\24\0"+
    "\1\1\12\2\6\0\6\1\4\0\4\1\3\0\1\1\3\0\2\1"+
    "\7\0\3\1\4\0\15\1\14\0\1\1\1\0\12\2\6\0\46\1"+
    "\1\0\1\1\5\0\1\1\2\0\53\1\1\0\u014d\1\1\0\4\1"+
    "\2\0\7\1\1\0\1\1\1\0\4\1\2\0\51\1\1\0\4\1"+
    "\2\0\41\1\1\0\4\1\2\0\7\1\1\0\1\1\1\0\4\1"+
    "\2\0\17\1\1\0\71\1\1\0\4\1\2\0\103\1\45\0\20\1"+
    "\20\0\126\1\2\0\6\1\3\0\u026c\1\2\0\21\1\1\0\32\1"+
    "\5\0\113\1\6\0\10\1\7\0\15\1\1\0\4\1\16\0\22\1"+
    "\16\0\22\1\16\0\15\1\1\0\3\1\17\0\64\1\43\0\1\1"+
    "\4\0\1\1\3\0\12\2\46\0\12\2\6\0\130\1\10\0\5\1"+
    "\2\0\42\1\1\0\1\1\5\0\106\1\12\0\37\1\47\0\12\2"+
    "\36\1\2\0\5\1\13\0\54\1\4\0\32\1\6\0\12\2\46\0"+
    "\27\1\11\0\65\1\53\0\12\2\6\0\12\2\15\0\1\1\135\0"+
    "\57\1\21\0\7\1\4\0\12\2\51\0\36\1\15\0\2\1\12\2"+
    "\54\1\32\0\44\1\34\0\12\2\3\0\3\1\12\2\44\1\2\0"+
    "\11\1\140\0\4\1\1\0\4\1\3\0\2\1\11\0\300\1\100\0"+
    "\u0116\1\2\0\6\1\2\0\46\1\2\0\6\1\2\0\10\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\37\1\2\0\65\1\1\0"+
    "\7\1\1\0\1\1\3\0\3\1\1\0\7\1\3\0\4\1\2\0"+
    "\6\1\4\0\15\1\5\0\3\1\1\0\7\1\53\0\1\44\1\44"+
    "\107\0\1\1\15\0\1\1\20\0\15\1\145\0\1\1\4\0\1\1"+
    "\2\0\12\1\1\0\1\1\3\0\5\1\6\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\4\1\1\0\13\1\2\0\4\1\5\0\5\1"+
    "\4\0\1\1\64\0\2\1\u0a7b\0\57\1\1\0\57\1\1\0\205\1"+
    "\6\0\4\1\3\0\2\1\14\0\46\1\1\0\1\1\5\0\1\1"+
    "\2\0\70\1\7\0\1\1\20\0\27\1\11\0\7\1\1\0\7\1"+
    "\1\0\7\1\1\0\7\1\1\0\7\1\1\0\7\1\1\0\7\1"+
    "\1\0\7\1\120\0\1\1\u01d5\0\2\1\52\0\5\1\5\0\2\1"+
    "\4\0\126\1\6\0\3\1\1\0\132\1\1\0\4\1\5\0\51\1"+
    "\3\0\136\1\21\0\33\1\65\0\20\1\u0200\0\u19b6\1\112\0\u51d6\1"+
    "\52\0\u048d\1\103\0\56\1\2\0\u010d\1\3\0\20\1\12\2\2\1"+
    "\24\0\57\1\20\0\37\1\2\0\106\1\61\0\11\1\2\0\147\1"+
    "\2\0\44\1\1\0\10\1\77\0\13\1\1\0\3\1\1\0\4\1"+
    "\1\0\27\1\35\0\64\1\16\0\62\1\34\0\12\2\30\0\6\1"+
    "\3\0\1\1\1\0\1\1\2\0\12\2\34\1\12\0\27\1\31\0"+
    "\35\1\7\0\57\1\34\0\1\1\12\2\6\0\5\1\1\0\12\1"+
    "\12\2\5\1\1\0\51\1\27\0\3\1\1\0\10\1\4\0\12\2"+
    "\6\0\27\1\3\0\1\1\3\0\62\1\1\0\1\1\3\0\2\1"+
    "\2\0\5\1\2\0\1\1\1\0\1\1\30\0\3\1\2\0\13\1"+
    "\7\0\3\1\14\0\6\1\2\0\6\1\2\0\6\1\11\0\7\1"+
    "\1\0\7\1\1\0\53\1\1\0\12\1\12\0\163\1\15\0\12\2"+
    "\6\0\u2ba4\1\14\0\27\1\4\0\61\1\u2104\0\u016e\1\2\0\152\1"+
    "\46\0\7\1\14\0\5\1\5\0\1\1\1\0\12\1\1\0\15\1"+
    "\1\0\5\1\1\0\1\1\1\0\2\1\1\0\2\1\1\0\154\1"+
    "\41\0\u016b\1\22\0\100\1\2\0\66\1\50\0\14\1\164\0\5\1"+
    "\1\0\207\1\23\0\12\2\7\0\32\1\6\0\32\1\13\0\131\1"+
    "\3\0\6\1\2\0\6\1\2\0\6\1\2\0\3\1\43\0\14\1"+
    "\1\0\32\1\1\0\23\1\1\0\2\1\1\0\17\1\2\0\16\1"+
    "\42\0\173\1\u0185\0\35\1\3\0\61\1\57\0\40\1\20\0\21\1"+
    "\1\0\10\1\6\0\46\1\12\0\36\1\2\0\44\1\4\0\10\1"+
    "\60\0\236\1\2\0\12\2\6\0\44\1\4\0\44\1\4\0\50\1"+
    "\10\0\64\1\234\0\u0137\1\11\0\26\1\12\0\10\1\230\0\6\1"+
    "\2\0\1\1\1\0\54\1\1\0\2\1\3\0\1\1\2\0\27\1"+
    "\12\0\27\1\11\0\37\1\101\0\23\1\1\0\2\1\12\0\26\1"+
    "\12\0\32\1\106\0\70\1\6\0\2\1\100\0\1\1\17\0\4\1"+
    "\1\0\3\1\1\0\33\1\54\0\35\1\3\0\35\1\43\0\10\1"+
    "\1\0\34\1\33\0\66\1\12\0\26\1\12\0\23\1\15\0\22\1"+
    "\156\0\111\1\67\0\63\1\15\0\63\1\u0310\0\65\1\56\0\12\2"+
    "\23\0\55\1\40\0\31\1\7\0\12\2\11\0\44\1\17\0\12\2"+
    "\20\0\43\1\3\0\1\1\14\0\60\1\16\0\4\1\13\0\12\2"+
    "\1\1\1\0\1\1\43\0\22\1\1\0\31\1\124\0\7\1\1\0"+
    "\1\1\1\0\4\1\1\0\17\1\1\0\12\1\7\0\57\1\21\0"+
    "\12\2\13\0\10\1\2\0\2\1\2\0\26\1\1\0\7\1\1\0"+
    "\2\1\1\0\5\1\3\0\1\1\22\0\1\1\14\0\5\1\236\0"+
    "\65\1\22\0\4\1\5\0\12\2\46\0\60\1\24\0\2\1\1\0"+
    "\1\1\10\0\12\2\246\0\57\1\51\0\4\1\44\0\60\1\24\0"+
    "\1\1\13\0\12\2\46\0\53\1\25\0\12\2\66\0\32\1\26\0"+
    "\12\2\u0166\0\100\1\12\2\25\0\1\1\u01c0\0\71\1\u0107\0\11\1"+
    "\1\0\45\1\21\0\1\1\17\0\12\2\30\0\36\1\u0370\0\u039a\1"+
    "\346\0\304\1\u0abc\0\u042f\1\u0fd1\0\u0247\1\u21b9\0\u0239\1\7\0\37\1"+
    "\1\0\12\2\146\0\36\1\22\0\60\1\20\0\4\1\14\0\12\2"+
    "\11\0\25\1\5\0\23\1\u0370\0\105\1\13\0\1\1\102\0\15\1"+
    "\100\0\1\1\37\0\u17ed\1\23\0\u02f3\1\u250d\0\2\1\u0bfe\0\153\1"+
    "\5\0\15\1\3\0\11\1\7\0\12\1\u1766\0\125\1\1\0\107\1"+
    "\1\0\2\1\2\0\1\1\2\0\2\1\2\0\4\1\1\0\14\1"+
    "\1\0\1\1\1\0\7\1\1\0\101\1\1\0\4\1\2\0\10\1"+
    "\1\0\7\1\1\0\34\1\1\0\4\1\1\0\5\1\1\0\1\1"+
    "\3\0\7\1\1\0\u0154\1\2\0\31\1\1\0\31\1\1\0\37\1"+
    "\1\0\31\1\1\0\37\1\1\0\31\1\1\0\37\1\1\0\31\1"+
    "\1\0\37\1\1\0\31\1\1\0\10\1\2\0\62\2\u1000\0\305\1"+
    "\73\0\104\1\14\0\12\2\u04a6\0\4\1\1\0\33\1\1\0\2\1"+
    "\1\0\1\1\2\0\1\1\1\0\12\1\1\0\4\1\1\0\1\1"+
    "\1\0\1\1\6\0\1\1\4\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\3\1\1\0\2\1\1\0\1\1\2\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\0\2\1\1\0\1\1"+
    "\2\0\4\1\1\0\7\1\1\0\4\1\1\0\4\1\1\0\1\1"+
    "\1\0\12\1\1\0\21\1\5\0\3\1\1\0\5\1\1\0\21\1"+
    "\u1144\0\ua6d7\1\51\0\u1035\1\13\0\336\1\2\0\u1682\1\u295e\0\u021e\1"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05f0\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\1\12\2\1\21\1\22\1\23\1\24\2\2"+
    "\1\25\4\2\1\26\4\2\1\27\2\2\1\30\2\2"+
    "\1\31\2\2\1\32\1\2\1\33\2\2\1\34\1\35"+
    "\1\2\1\36\3\2\1\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[66];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\112\0\157\0\45\0\45\0\45\0\45"+
    "\0\224\0\45\0\271\0\45\0\45\0\45\0\45\0\45"+
    "\0\45\0\336\0\u0103\0\u0128\0\u014d\0\u0172\0\u0197\0\u01bc"+
    "\0\u01e1\0\u0206\0\u022b\0\u0250\0\45\0\45\0\45\0\45"+
    "\0\u0275\0\u029a\0\112\0\u02bf\0\u02e4\0\u0309\0\u032e\0\112"+
    "\0\u0353\0\u0378\0\u039d\0\u03c2\0\112\0\u03e7\0\u040c\0\112"+
    "\0\u0431\0\u0456\0\112\0\u047b\0\u04a0\0\112\0\u04c5\0\112"+
    "\0\u04ea\0\u050f\0\112\0\112\0\u0534\0\112\0\u0559\0\u057e"+
    "\0\u05a3\0\112";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[66];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\3\1\25\1\3\1\26\2\3"+
    "\1\27\1\3\1\30\1\31\1\3\1\32\3\3\1\33"+
    "\1\34\47\0\2\3\16\0\23\3\3\0\1\4\52\0"+
    "\1\35\1\36\43\0\1\37\44\0\1\40\35\0\2\3"+
    "\16\0\1\3\1\41\21\3\2\0\2\3\16\0\4\3"+
    "\1\42\16\3\2\0\2\3\16\0\14\3\1\43\6\3"+
    "\2\0\2\3\16\0\6\3\1\44\1\3\1\45\12\3"+
    "\2\0\2\3\16\0\13\3\1\46\7\3\2\0\2\3"+
    "\16\0\20\3\1\47\2\3\2\0\2\3\16\0\10\3"+
    "\1\50\12\3\2\0\2\3\16\0\16\3\1\51\4\3"+
    "\2\0\2\3\16\0\6\3\1\52\14\3\2\0\2\3"+
    "\16\0\20\3\1\53\2\3\2\0\2\3\16\0\2\3"+
    "\1\54\20\3\2\0\2\3\16\0\13\3\1\55\7\3"+
    "\2\0\2\3\16\0\7\3\1\56\13\3\2\0\2\3"+
    "\16\0\4\3\1\57\16\3\2\0\2\3\16\0\13\3"+
    "\1\60\7\3\2\0\2\3\16\0\1\3\1\61\21\3"+
    "\2\0\2\3\16\0\10\3\1\62\12\3\2\0\2\3"+
    "\16\0\16\3\1\63\4\3\2\0\2\3\16\0\3\3"+
    "\1\64\17\3\2\0\2\3\16\0\3\3\1\65\17\3"+
    "\2\0\2\3\16\0\7\3\1\66\13\3\2\0\2\3"+
    "\16\0\11\3\1\67\11\3\2\0\2\3\16\0\4\3"+
    "\1\70\16\3\2\0\2\3\16\0\5\3\1\71\15\3"+
    "\2\0\2\3\16\0\7\3\1\72\13\3\2\0\2\3"+
    "\16\0\4\3\1\73\16\3\2\0\2\3\16\0\12\3"+
    "\1\74\10\3\2\0\2\3\16\0\1\3\1\75\21\3"+
    "\2\0\2\3\16\0\1\3\1\76\21\3\2\0\2\3"+
    "\16\0\13\3\1\77\7\3\2\0\2\3\16\0\17\3"+
    "\1\100\3\3\2\0\2\3\16\0\16\3\1\101\4\3"+
    "\2\0\2\3\16\0\1\3\1\102\21\3\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1480];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\4\11\1\1\1\11\1\1\6\11"+
    "\13\1\4\11\42\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[66];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  private SymbolFactory symbolFactory;

  public PL0Lexer (java.io.Reader input, SymbolFactory sf) {
    this (input);
    symbolFactory = sf;
  }

  private void echo () { System . out . print (yytext ()); }

  public int position () { return yycolumn; }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  PL0Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2590) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {   return symbolFactory.newSymbol ("EOF", Symbol . EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { echo (); ErrorMessage . print (yychar, "Illegal character");
            } 
            // fall through
          case 32: break;
          case 2: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(identifier, " + yytext () + ")", 
                      Symbol . ID, yytext ());
            } 
            // fall through
          case 33: break;
          case 3: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(integer, " + yytext () + ")", 
                      Symbol . INTEGER, yytext ());
            } 
            // fall through
          case 34: break;
          case 4: 
            { echo ();
            } 
            // fall through
          case 35: break;
          case 5: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(punctuation, ;)", Symbol . SEMICOLON);
            } 
            // fall through
          case 36: break;
          case 6: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(punctuation, .)", Symbol . PERIOD);
            } 
            // fall through
          case 37: break;
          case 7: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(punctuation, ,)", Symbol . COMMA);
            } 
            // fall through
          case 38: break;
          case 8: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, <)", Symbol . LT);
            } 
            // fall through
          case 39: break;
          case 9: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, =)", Symbol . EQ);
            } 
            // fall through
          case 40: break;
          case 10: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, >)", Symbol . GT);
            } 
            // fall through
          case 41: break;
          case 11: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, ()", Symbol . LPAREN);
            } 
            // fall through
          case 42: break;
          case 12: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, ))", Symbol . RPAREN);
            } 
            // fall through
          case 43: break;
          case 13: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, +)", Symbol . PLUS);
            } 
            // fall through
          case 44: break;
          case 14: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, -)", Symbol . MINUS);
            } 
            // fall through
          case 45: break;
          case 15: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, *)", Symbol . TIMES);
            } 
            // fall through
          case 46: break;
          case 16: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, /)", Symbol . SLASH);
            } 
            // fall through
          case 47: break;
          case 17: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, <=)", Symbol . LE);
            } 
            // fall through
          case 48: break;
          case 18: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, <>)", Symbol . NE);
            } 
            // fall through
          case 49: break;
          case 19: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, >=)", Symbol . GE);
            } 
            // fall through
          case 50: break;
          case 20: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, :=)", Symbol . ASSIGN);
            } 
            // fall through
          case 51: break;
          case 21: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, if)", Symbol . IF);
            } 
            // fall through
          case 52: break;
          case 22: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, do)", Symbol . DO);
            } 
            // fall through
          case 53: break;
          case 23: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, end)", Symbol . END);
            } 
            // fall through
          case 54: break;
          case 24: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, odd)", Symbol . ODD);
            } 
            // fall through
          case 55: break;
          case 25: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, var)", Symbol . VAR);
            } 
            // fall through
          case 56: break;
          case 26: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, end)", Symbol . CALL);
            } 
            // fall through
          case 57: break;
          case 27: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, then)", Symbol . THEN);
            } 
            // fall through
          case 58: break;
          case 28: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, begin)", Symbol . BEGIN);
            } 
            // fall through
          case 59: break;
          case 29: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, const)", Symbol . CONST);
            } 
            // fall through
          case 60: break;
          case 30: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, while)", Symbol . WHILE);
            } 
            // fall through
          case 61: break;
          case 31: 
            { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, procedure)", Symbol . PROC);
            } 
            // fall through
          case 62: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
